// login.http実施後に、tokenを差し替える
GET http://localhost:3000/admin/api/v1/login/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MjM0ODcxNDYsImV4cCI6MTYyMzQ4Nzc0Nn0.5vHDZyLXrTOssv5SZYao-2nkMiqt1yaQUTzYXT1a0iI