version: '3'

services:
  api:
    tty: true
    build:
      context: ./api
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 3000:3000
    #command: 'yarn dev'
    depends_on:
      - db
  cms:
    tty: true
    build:
      context: ./cms
    volumes:
      - ./cms/:/usr/src/app
    ports:
      - 3002:3000
  cms_server:
    image: nginx:latest
    ports:
      - 8002:80
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d:ro
      - ./cms/:/var/www/html
    working_dir: /var/www/html
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample
    ports:
      - 5435:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data