version: '3'

services:
  api:
    tty: true
    build: '.'
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    #command: 'yarn dev'
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample
    ports:
      - 5435:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data